const DATA=[
    {name:'Location',
    source:require('/../src/assets/Location.png'),
    id:1,
    },
    {name:'Website',
    source:require('/../src/assets/website.png'),
    id:2,
    },
    {name:'Fax',
    source:require('/../src/assets/Fax.png'),
    id:3,
    },
    {name:'FaceBook',
    source:require('/../src/assets/Facebook.png'),
    id:4,
    },
    {name:'Linkedin',
    source:require('/../src/assets/Linkedin.png'),
    id:5,
    },
    {name:'Twitter',
    source:require('/../src/assets/Twitter.png'),
    id:6,
    },
    {name:'Tumblr',
    source:require('/../src/assets/Tumblr.png'),
    id:7,
    },
    {name:'Whatsapp',
    source:require('/../src/assets/Whatsapp.png'),
    id:8,
    },
    

];

export {DATA};