const DATA=[    
   {value:'Taqi Sleel',
   key:1,
   designation:'Co-Founder at PhoneShake Inc.',
   bio:'Hello PhoneShake user. I live here in your contacts. Have a question? Feel free to contact me or just say hi.',
   imgsrc:require('/../src/assets/PhoneShake_Icon.png'),
   },
   {value:'Aaqi Sleel',
   key:2,
   designation:'Co-Founder at PhoneShake Inc.',
   bio:'Hello PhoneShake user. I live here in your contacts. Have a question? Feel free to contact me or just say hi.',
   imgsrc:require('/../src/assets/PhoneShake_Icon.png'),
   },
   {value:'Vaqi Sleel',
   key:3,
   designation:'Co-Founder at PhoneShake Inc.',
   bio:'Hello PhoneShake user. I live here in your contacts. Have a question? Feel free to contact me or just say hi.',
   imgsrc:require('/../src/assets/PhoneShake_Icon.png'),
   },
   {value:'Daqi Sleel',
   key:4,
   designation:'Co-Founder at PhoneShake Inc.',
   bio:'Hello PhoneShake user. I live here in your contacts. Have a question? Feel free to contact me or just say hi.',
   imgsrc:require('/../src/assets/PhoneShake_Icon.png'),
   },
   {value:'Taqi Sleel',
   key:5,
   designation:'Co-Founder at PhoneShake Inc.',
   bio:'Hello PhoneShake user. I live here in your contacts. Have a question? Feel free to contact me or just say hi.',
   imgsrc:require('/../src/assets/PhoneShake_Icon.png'),
   },
   {value:'Naqi Sleel',
   key:6,
   designation:'Co-Founder at PhoneShake Inc.',
   bio:'Hello PhoneShake user. I live here in your contacts. Have a question? Feel free to contact me or just say hi.',
   imgsrc:require('/../src/assets/PhoneShake_Icon.png'),
   },
   {value:'Raqi Sleel',
   key:7,
   designation:'Co-Founder at PhoneShake Inc.',
   bio:'Hello PhoneShake user. I live here in your contacts. Have a question? Feel free to contact me or just say hi.',
   imgsrc:require('/../src/assets/PhoneShake_Icon.png'),
   },
   {value:'Maqi Sleel',
   key:8,
   designation:'Co-Founder at PhoneShake Inc.',
   bio:'Hello PhoneShake user. I live here in your contacts. Have a question? Feel free to contact me or just say hi.',
   imgsrc:require('/../src/assets/PhoneShake_Icon.png'),
   },
   {value:'Aaqi Sleel',
   key:9,
   designation:'Co-Founder at PhoneShake Inc.',
   bio:'Hello PhoneShake user. I live here in your contacts. Have a question? Feel free to contact me or just say hi.',
   imgsrc:require('/../src/assets/PhoneShake_Icon.png'),
   },
   {value:'Laqi Sleel',
   key:10,
   designation:'Co-Founder at PhoneShake Inc.',
   bio:'Hello PhoneShake user. I live here in your contacts. Have a question? Feel free to contact me or just say hi.',
   imgsrc:require('/../src/assets/PhoneShake_Icon.png'),
   },
    
]

export {DATA};